/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avli;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tatiana
 */
public class View extends javax.swing.JFrame {
         AVL tree = new AVL();
         
    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        InsertButton = new javax.swing.JButton();
        DeleteField = new javax.swing.JTextField();
        DeleteButton = new javax.swing.JButton();
        FindButton = new javax.swing.JButton();
        findField = new javax.swing.JTextField();
        hightLabel = new javax.swing.JLabel();
        preordenButton = new javax.swing.JButton();
        posordenButton = new javax.swing.JButton();
        inordenButton = new javax.swing.JButton();
        dfsButton = new javax.swing.JButton();
        bfsButton = new javax.swing.JButton();
        numberElementsLabel = new javax.swing.JLabel();
        rootLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        InsertField = new javax.swing.JTextField();
        recorridoLabel = new javax.swing.JLabel();
        fullTreeLabel = new javax.swing.JLabel();
        completeLabel = new javax.swing.JLabel();
        ancestorsButton = new javax.swing.JButton();
        ancestorsTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Árboles binarios de búsqueda");
        setBackground(javax.swing.UIManager.getDefaults().getColor("window"));

        InsertButton.setText("Insertar");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Eliminar");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        FindButton.setText("Buscar");
        FindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindButtonActionPerformed(evt);
            }
        });

        hightLabel.setForeground(new java.awt.Color(102, 0, 102));
        hightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hightLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        preordenButton.setText("Preorden");
        preordenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preordenButtonActionPerformed(evt);
            }
        });

        posordenButton.setText("Posorden");
        posordenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posordenButtonActionPerformed(evt);
            }
        });

        inordenButton.setText("Inorden");
        inordenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inordenButtonActionPerformed(evt);
            }
        });

        dfsButton.setText("DFS");
        dfsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dfsButtonActionPerformed(evt);
            }
        });

        bfsButton.setText("BFS");
        bfsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfsButtonActionPerformed(evt);
            }
        });

        numberElementsLabel.setForeground(new java.awt.Color(102, 0, 102));
        numberElementsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        InsertField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertFieldActionPerformed(evt);
            }
        });

        recorridoLabel.setForeground(new java.awt.Color(102, 0, 102));

        fullTreeLabel.setForeground(new java.awt.Color(102, 0, 102));

        completeLabel.setForeground(new java.awt.Color(102, 0, 102));

        ancestorsButton.setText("Ancestros");
        ancestorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ancestorsButtonActionPerformed(evt);
            }
        });

        ancestorsTextField.setSelectionColor(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(rootLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(InsertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InsertField, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(completeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DeleteField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(findField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fullTreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(numberElementsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ancestorsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ancestorsTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inordenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preordenButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posordenButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bfsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dfsButton))
                            .addComponent(recorridoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(rootLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recorridoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(findField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DeleteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(InsertField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numberElementsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fullTreeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ancestorsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(completeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dfsButton)
                                    .addComponent(bfsButton)
                                    .addComponent(posordenButton)
                                    .addComponent(preordenButton)
                                    .addComponent(inordenButton)
                                    .addComponent(FindButton)
                                    .addComponent(DeleteButton)
                                    .addComponent(InsertButton)
                                    .addComponent(ancestorsButton))))))
                .addGap(7, 7, 7))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    /*permite graficar un árbol binario*/
    private void drawTree(Graphics g, NodeAVL sheet, int x, int y,int xangle,int yangle,int level){
     if (sheet == null) return;
     
     if(sheet.getLeftChild()!= null){
         g.setColor(Color.black);
         g.drawLine(x, y, x - xangle+(sheet.height*4), y + yangle );
     }
     if(sheet.getRightChild()!= null){
         g.setColor(Color.black);
         g.drawLine(x, y, x + xangle-(sheet.height*8), y + yangle);
     }
     g.setColor(Color.pink);
    
     g.fill3DRect(x-10, y-20, 35+sheet.height*4, 35, rootPaneCheckingEnabled);
     
     g.setColor(Color.black);
     g.drawString(sheet.data+"", x , y );
     if(sheet.getLeftChild()!=null){
        drawTree(g, sheet.getLeftChild(), (int)(x - xangle), (y + yangle),xangle+level*2,yangle,level+1); 
     }
     if((sheet.getRightChild()!=null) && (sheet.rightChild.data != sheet.data)){
     drawTree(g, sheet.getRightChild(), (int)(x + xangle), (y + yangle),xangle-level*2,yangle,level+1);
        }
     }

    @Override
    public void paint(Graphics g){
        jPanel1.revalidate();
        jPanel1.setBackground(Color.white);
        super.paint(g);
        int X = getWidth()/7;
        int Y = getHeight()/5;
        drawTree(jPanel1.getGraphics(), tree.getRoot(), jPanel1.getWidth()/2, Y, X, Y,1);
        
    }
    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
     try{
        tree.setTotalNodes(0);
        if (InsertField.getText()!=null){
        tree.Insert(Integer.parseInt(InsertField.getText()));
        InsertField.setText(null);
        hightLabel.setText(String.valueOf("Altura: "+tree.getheight(tree.getRoot())));
        tree.inOrder(tree.getRoot());
        numberElementsLabel.setText("Número de Elementos: "+String.valueOf(tree.getTotalNodes()));
        fullTreeLabel.setText("Lleno: "+ tree.fullTree(tree.getRoot(), tree.getTotalNodes()));
        completeLabel.setText("Completo: "+ tree.isComplete(tree.getRoot()));
        paint(jPanel1.getGraphics());
       
        }
       } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: "+e);
        }
        InsertField.setText(null);
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void InsertFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertFieldActionPerformed
   
    }//GEN-LAST:event_InsertFieldActionPerformed

    private void bfsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfsButtonActionPerformed
        try{
        recorridoLabel.setText("");
        recorridoLabel.setText(tree.orderBFS(tree.getRoot()));
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,"Error: " + e);
        }
    }//GEN-LAST:event_bfsButtonActionPerformed

    private void inordenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inordenButtonActionPerformed
        // TODO add your handling code here:
        tree.inorden = "";
        recorridoLabel.setText("");
        recorridoLabel.setText("Recorrido inorden: "+tree.inOrder(tree.getRoot()));
    }//GEN-LAST:event_inordenButtonActionPerformed

    private void preordenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preordenButtonActionPerformed
        // TODO add your handling code here:
        tree.preorden= "";
        recorridoLabel.setText("");
        recorridoLabel.setText("Recorrido preorden: "+tree.preOrder(tree.getRoot()));
    }//GEN-LAST:event_preordenButtonActionPerformed

    private void posordenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posordenButtonActionPerformed
        // TODO add your handling code here:
        tree.posorden = "";
        recorridoLabel.setText("");
        recorridoLabel.setText("Recorrido posorden: "+tree.postOrder(tree.getRoot()));
    }//GEN-LAST:event_posordenButtonActionPerformed

    private void dfsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dfsButtonActionPerformed
        // TODO add your handling code here:
        try{
        recorridoLabel.setText("");
        recorridoLabel.setText(tree.orderDFS(tree.getRoot()));
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error" + e);
        }
    }//GEN-LAST:event_dfsButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        tree.setTotalNodes(0);
        try{
        if(DeleteField.getText()!= null && tree.getRoot()!=null){
        tree.delete(Integer.parseInt(DeleteField.getText()));
        }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: "+e);
        }
        paint(jPanel1.getGraphics());
        hightLabel.setText(String.valueOf("Altura: "+tree.getheight(tree.getRoot())));
        tree.inOrder(tree.getRoot());
        numberElementsLabel.setText("Número de Elementos: " + String.valueOf(tree.getTotalNodes()));
        DeleteField.setText(null);
    
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void FindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindButtonActionPerformed
        // TODO add your handling code here:
       try{
       boolean result = tree.findData(Integer.parseInt(findField.getText()));
       if (result == true){ JOptionPane.showMessageDialog(this, "Encontrado");
       }else{
           JOptionPane.showMessageDialog(this, "No Encontrado");
       }
       findField.setText(null);
    }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: "+e);
        }
    }//GEN-LAST:event_FindButtonActionPerformed

    private void ancestorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ancestorsButtonActionPerformed
        // TODO add your handling code here:
        try{
        recorridoLabel.setText(tree.printAncestors(tree.getRoot(), Integer.parseInt(ancestorsTextField.getText())));
        ancestorsTextField.setText(null);
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error" +e);
        }
    }//GEN-LAST:event_ancestorsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField DeleteField;
    private javax.swing.JButton FindButton;
    private javax.swing.JButton InsertButton;
    private javax.swing.JTextField InsertField;
    private javax.swing.JButton ancestorsButton;
    private javax.swing.JTextField ancestorsTextField;
    private javax.swing.JButton bfsButton;
    private javax.swing.JLabel completeLabel;
    private javax.swing.JButton dfsButton;
    private javax.swing.JTextField findField;
    private javax.swing.JLabel fullTreeLabel;
    private javax.swing.JLabel hightLabel;
    private javax.swing.JButton inordenButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel numberElementsLabel;
    private javax.swing.JButton posordenButton;
    private javax.swing.JButton preordenButton;
    private javax.swing.JLabel recorridoLabel;
    private javax.swing.JLabel rootLabel;
    // End of variables declaration//GEN-END:variables
}
